apiVersion: apps/v1
kind: Deployment
metadata:
  name: flask-app
spec:
  selector:
    matchLabels:
      app: flask-app
  replicas: 3
  template:
    metadata:
      labels:
        app: flask-app
    spec:
      containers:
        - name: flask-app
          image: <your-docker-registry>/flask-app
          ports:
            - containerPort: 5000
      imagePullSecrets:
        - name: <your-docker-registry-secret>
---
apiVersion: v1
kind: Service
metadata:
  name: flask-app-service
spec:
  selector:
    app: flask-app
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: 5000
      protocol: TCP

